package com.example.mms.constant

val listHealthDiseases = listOf(
    "Asthme",
    "Diabète",
    "Hypertension",
    "Cancer",
    "Arthrite",
    "Migraine",
    "Maladie de Crohn",
    "Sclérose en plaques",
    "Fibromyalgie",
    "Parkinson"
)

val listDietPlan = listOf(
    "Végétarien",
    "Végétalien",
    "Sans gluten",
    "Cétogène",
    "Paléo",
    "Méditerranéen",
    "Sans lactose",
    "DASH",
    "Flexitarien",
    "Weight Watchers"
)
/*
val listAllergies = listOf(
    "Arachides",
    "Lait",
    "Blé",
    "Fruits à coque",
    "Soja",
    "Oeufs",
    "Poisson",
    "Crustacés",
    "Sésame",
    "Moutarde"
)
*/
val listAllergies = listOf(
    "Blé",
    "Tiaprofénique",
    "AINS",
    "Acide acétylsalicylique",
    "Constituant",
    "Anesthésiques",
    "Cromoglicate de sodium",
    "Naproxène",
    "Sodique",
    "Soja",
    "Céphalosporines",
    "Salicylés",
    "Chlorhexidine",
    "Ibuprofène",
    "Antihistaminiques",
    "Astéracées",
    "D’huile d’arachide",
    "Photosensibilité",
    "Céthexonium",
    "Arachine",
    "Carboplatine",
    "Céfuroxime",
    "Lysozyme",
    "Excipients",
    "Macrolides",
    "Foins",
    "Urticaire",
    "Aspirine",
    "Anti-inflammatoires non stéroïdiens",
    "Hexamidine",
    "Tétracyclines",
    "Angiœdème",
    "Angio-œdème",
    "Rhinite aiguë",
    "Diclofénac",
    "Paracétamol",
    "Maïs",
    "Fénofibrate",
    "Kétoprofène",
    "Piroxicam",
    "Fibrates",
    "Atopiques",
    "Lactose",
    "Formotérol",
    "Furosémide",
    "Sulfonamides",
    "Sulfamides",
    "Viande rouge",
    "Abats",
    "Escargots",
    "Tropomyosine",
    "Prostaglandines",
    "Héparines",
    "Héparinoïdes",
    "Ammoniums",
    "Indométacine",
    "Lévocétirizine",
    "Cétirizine",
    "Hydroxyzine",
    "Pipérazine",
    "Sulfamides",
    "Chélates",
    "Mupirocine",
    "Polyéthylène",
    "Glycol",
    "Macrogol",
    "Niflumique",
    "Morniflumate",
    "Thrombocytes",
    "Flurbiprofène",
    "Phénoxyméthylpénicilline",
    "Pénicillines",
    "Théophylline",
    "Méfénamique",
    "Benzocaïne",
    "Atropine",
    "Ipratropium",
    "Oxitropium",
    "Tiotropium",
    "Formaldéhyde",
    "Néomycine",
    "Gentamicine",
    "Protamine",
    "Chlorhydrate",
    "Amide",
    "Sulfite",
    "Salbutamol",
    "Monohydraté",
    "Cobalamines",
    "Parahydroxybenzoates",
    "Parabens",
    "Méthylparaben",
    "Propylparaben",
    "Butylparaben",
    "Éthylparaben",
    "Isobutylparaben",
    "Isopropylparaben"
)